version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # - ./:/home/backend
      - dae-volume:/home/backend
    ports:
      - "7717:8000"
    environment:
      TZ: Asia/Seoul

volumes:
  dae-volume:
    external:
      name: dae_volume